trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob  
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps:
    - bash: echo $(environment)DeployJob
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  dependsOn:
  - QADeploy
  - DevDeploy
  jobs:
  - job: ProdDeploy
    variables:
      environment: Prod
    steps:
    - bash: echo $(environment)DeployJob


